//这个文件是你当前组件所在的路由位置
export const homePage = '/app/home'
export const community = '/app/home/community'
export const market = '/app/home/market/marketContent'
export const store='/app/home/market/store'
export const homeContent='/app/home/homeContent'
export const communityContent='/app/home/community/CommunityContent'
export const logo='/app/logo'
export const login='/app/login'
export const marketRoute='/app/home/market'